package handlers_test

import (
	"image"
	"image/color"
	"image/png"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/lepinkainen/sampo/internal/analysis"
	"github.com/lepinkainen/sampo/internal/config"
	"github.com/lepinkainen/sampo/internal/filesystem"
	"github.com/lepinkainen/sampo/internal/server/handlers"
	"github.com/lepinkainen/sampo/internal/thumbnail"
)

func writeThumbTestPNG(t *testing.T, path string, width, height int) {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	for y := range height {
		for x := range width {
			img.Set(x, y, color.RGBA{R: 0, G: 128, B: 255, A: 255})
		}
	}
	f, err := os.Create(path)
	if err != nil {
		t.Fatalf("creating test image: %v", err)
	}
	defer f.Close()
	if err := png.Encode(f, img); err != nil {
		t.Fatalf("encoding test image: %v", err)
	}
}

func serveThumbWithChi(h *handlers.Handler, path string) *httptest.ResponseRecorder {
	r := chi.NewRouter()
	r.Get("/api/thumb/{rootID}/*", h.GetThumbnail)
	req := httptest.NewRequest(http.MethodGet, path, nil)
	rr := httptest.NewRecorder()
	r.ServeHTTP(rr, req)
	return rr
}

// TestGetThumbnail_DeferredImageReturnsThumbnail verifies that when auto-browse
// analysis is on, a cache-miss image thumbnail is generated by the coordinator
// worker and served once its completion channel closes (HTTP 200, valid JPEG).
func TestGetThumbnail_DeferredImageReturnsThumbnail(t *testing.T) {
	rootDir := t.TempDir()
	imgPath := filepath.Join(rootDir, "photo.png")
	writeThumbTestPNG(t, imgPath, 320, 240)
	info, err := os.Stat(imgPath)
	if err != nil {
		t.Fatal(err)
	}

	roots, err := filesystem.NewRootManager([]config.RootConfig{
		{Name: "test", Path: rootDir},
	})
	if err != nil {
		t.Fatal(err)
	}

	cache, err := thumbnail.NewCache(filepath.Join(t.TempDir(), "thumbs"))
	if err != nil {
		t.Fatal(err)
	}

	h := handlers.New(roots, cache, t.TempDir(), slog.Default())

	coord := analysis.NewCoordinator(nil, nil, nil, nil, nil, nil, nil, t.TempDir(), 1, 1, false, slog.Default())
	coord.SetThumbnailCache(cache)
	h.SetBrowseCoordinator(coord)
	h.SetAutoBrowseEnabled(true)

	rr := serveThumbWithChi(h, "/api/thumb/root-0/photo.png")
	if rr.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}

	if ct := rr.Header().Get("Content-Type"); !strings.HasPrefix(ct, "image/") {
		t.Errorf("expected image/* Content-Type, got %q", ct)
	}

	body := rr.Body.Bytes()
	if len(body) < 2 || body[0] != 0xFF || body[1] != 0xD8 {
		t.Errorf("response body is not a valid JPEG, got % x", body[:min(len(body), 4)])
	}

	key := thumbnail.CacheKey("root-0", "photo.png", info.ModTime().Unix(), info.Size())
	if _, ok := cache.Get("root-0", key); !ok {
		t.Error("thumbnail not cached after deferred generation")
	}
}

// TestGetThumbnail_DeferredImageFallsBackToSyncOnWorkerFailure verifies that
// when the coordinator worker cannot produce a thumbnail (undecodable image),
// the handler falls through to synchronous generation which returns a
// definitive 500 — not a 202 retry loop.
func TestGetThumbnail_DeferredImageFallsBackToSyncOnWorkerFailure(t *testing.T) {
	rootDir := t.TempDir()
	imgPath := filepath.Join(rootDir, "photo.jpg")
	if err := os.WriteFile(imgPath, []byte("not a real image"), 0644); err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(imgPath)
	if err != nil {
		t.Fatal(err)
	}

	roots, err := filesystem.NewRootManager([]config.RootConfig{
		{Name: "test", Path: rootDir},
	})
	if err != nil {
		t.Fatal(err)
	}

	cache, err := thumbnail.NewCache(filepath.Join(t.TempDir(), "thumbs"))
	if err != nil {
		t.Fatal(err)
	}

	h := handlers.New(roots, cache, t.TempDir(), slog.Default())

	coord := analysis.NewCoordinator(nil, nil, nil, nil, nil, nil, nil, t.TempDir(), 1, 1, false, slog.Default())
	coord.SetThumbnailCache(cache)
	h.SetBrowseCoordinator(coord)
	h.SetAutoBrowseEnabled(true)

	rr := serveThumbWithChi(h, "/api/thumb/root-0/photo.jpg")
	if rr.Code != http.StatusInternalServerError {
		t.Fatalf("expected 500 (sync fallback fails on corrupt image), got %d: %s", rr.Code, rr.Body.String())
	}

	key := thumbnail.CacheKey("root-0", "photo.jpg", info.ModTime().Unix(), info.Size())
	if _, ok := cache.Get("root-0", key); ok {
		t.Error("thumbnail should not exist for undecodable image")
	}
}
